import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "./components/SideMenu";
import Logo from "./components/Logo";
import { div } from "framer-motion/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="z-20 fixed left-12 top-12">
          <Logo />
        </div>
        <div className="z-20 absolute">
          <SideMenu />
        </div>
        {children}
      </body>
    </html>
  );
}
